### ISSUE TITLE
Summarize and show.

### ISSUE THREAD

**Issue by akshatvg** [CodeChefVIT/PP-Summarizer#1]
Work on this exclusive project from scratch and develop something to be used by thousands.

## About Summarizer
It is very tedious to read a long privacy policy or terms & conditions of a website or company. PP Summarizer helps the user choose the type of document or text and summarizes it within seconds.

## Features
- Summarize long privacy policies.
- Summarize long terms and conditions.

**Comment by subhadeep1912** [comment]
I would like to ask how can I contribute since you started an issue

**Comment by akshatvg** [comment]
Hey @subhadeep1912!

This project has just come out of the ideation stage and will be worked upon from scratch. You can start working on the project how ever you like, using whatever Tech Stack you deem fit.

**Comment by akshatvg** [comment]
@subhadeep1912 would you be working on it? 

Should I assign you to it?

**Comment by RajatSablok** [comment]
@akshatvg I'll take this one if no one else is doing it

**Comment by akshatvg** [comment]
Sure @RajatSablok. I’ve assigned you to it.
